#!/usr/bin/env bash
# Installing nginx web serer

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World" > /var/www/html/index.html

sudo nginx -t
sudo service nginx restart
