#!/usr/bin/env bash
# Script configuring a newubuntu machine to requirements stated

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null

redirect_config="
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}"

echo "$redirect_config" | sudo tee /etc/nginx/sites-available/redirect >/dev/null
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/
sudo rm -f /etc/nginx/sites-enabled/default
sudo nginx -t
sudo systemctl restart nginx