#!/usr/bin/env bash
# Config Nginx custom http response header
sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html

echo "Hello World!" | sudo tee /var/www/html/index.html

string_rep="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Rugut-dev permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_rep="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# restart the web server
sudo service nginx restart