#!/usr/bin/env bash
# Displays To infinity and beyond indefinitely with a sleep 2

cleaner() {
    echo "I am invincible!!!"
}

trap 'cleaner' SIGTERM

i=0
while ((i < 2))
do
    echo "To infinity and beyond"
    sleep 2
done
