#!/usr/bin/env bash
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

counter=0
phrase="Best School"
phrase1="bad luck"
phrase2="good luck"

while [ $counter -lt 10 ]
do
    if [ $counter -eq 3 ]
    then
	echo "$phrase1"
    elif [ $counter -eq 7 ]
    then
	echo "$phrase2"
    else
	echo "$phrase"
    fi
    ((counter++))
done
