#!/usr/bin/env bash
# displays number from 1 to 20
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

counter=1
phrase4="bad luck from China"
phrase9="bad luck from Japan"
phrase17="bad luck from Italy"

while [ $counter -le 20 ]
do
    case $counter in
	4)
	    echo "$counter"
	    echo "$phrase4"
	    ;;
	9)
	    echo "$counter"
	    echo "$phrase9"
	    ;;
	17)
	    echo "$counter"
	    echo "$phrase17"
	    ;;
	*)
	    echo "$counter"
    esac
    ((counter++))
done
