#!/usr/bin/env bash
# Displays the content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

LIST="$(ls)"
for i in $LIST
do
    if [ ! -h "$i" ] && [ -f "$i" ] && [ "$i" != ".*" ]
    then
	filename=$(echo "$i" | cut -d'-' -f2-)
	echo "$filename"
    fi
done
