#!/usr/bin/env bash
# COnfigures an ubuntu server hosts file

cp /etc/hosts orig_hosts
sed -i s/^127.*/"127.0.0.2 localhost"/ orig_hosts
echo "8.8.8.8 facebook.com" >> orig_hosts
cp orig_hosts /etc/hosts